# Generated by Django 5.2 on 2025-04-13 22:16

import api_video.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('data', models.DateField(auto_now_add=True)),
                ('arquivo', models.FileField(upload_to='')),
                ('thumbnail', models.ImageField(upload_to=api_video.models.RenameImage('imagens/'))),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('data', models.DateField(auto_now_add=True)),
                ('thumbnail', models.ImageField(upload_to=api_video.models.RenameImage('imagens/'))),
                ('videos', models.ManyToManyField(to='api_video.video')),
            ],
        ),
    ]
