# Generated by Django 5.2 on 2025-05-25 16:17

import api_video.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_video', '0002_remove_playlist_videos_playlistvideo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to=api_video.models.RenameImage('imagens/')),
        ),
        migrations.AlterField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to=api_video.models.RenameImage('imagens/')),
        ),
    ]
