# Generated by Django 5.2.1 on 2025-06-10 13:30

import api_video.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_video', '0003_alter_playlist_thumbnail_alter_video_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='arquivo',
            field=models.FileField(upload_to=api_video.models.RenameVideo('videos/')),
        ),
    ]
